steps:
  - name: 'google/cloud-sdk:slim'
    id: 'Deploy Data Layer Testing GCF'
    entrypoint: 'gcloud'
    waitFor:
      - '-'
    args: [
        'functions', 'deploy', '${_SERVICE_NAME}',
        '--runtime', 'python39',
        '--trigger-http',
        '--allow-unauthenticated',
        '--set-env-vars', 'GCP_REGION=${_REGION},GCP_PROJECT=${PROJECT_ID}',
        '--set-secrets', 'ERROR_LOG_TOKEN=${_ERROR_LOG_TOKEN_SECRET_NAME}:${_ERROR_LOG_TOKEN_SECRET_VERSION}',
        '--entry-point', '${_ENTRY_POINT}',
        '--timeout', '540s',
        '--memory', '512MB',
        '--region', '${_REGION}',
        '--project', '${PROJECT_ID}'
    ]
timeout: 1200s
substitutions:
  _SERVICE_NAME: "datalayer-tests-push"
  _REGION: "us-central1"
  _ENTRY_POINT: "main_handler"
  _ERROR_LOG_TOKEN_SECRET_NAME: "data-layer-error-log-token"
  _ERROR_LOG_TOKEN_SECRET_VERSION: "latest"

options:
  logging: 'CLOUD_LOGGING_ONLY'
