steps:
  - name: 'google/cloud-sdk:slim'
    id: 'Deploy Data Layer Testing GCF'
    entrypoint: 'gcloud'
    waitFor:
      - '-'
    args: [
        'functions', 'deploy', 'data-layer-tests',
        '--source', 'https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/moveable-aliases/${BRANCH_NAME}/paths/data_layer_collector',
        '--runtime', 'python39',
        '--trigger-http',
        '--allow-unauthenticated',
        '--set-env-vars', 'GCP_REGION=${_REGION},GCP_PROJECT=${PROJECT_ID}',
        '--entry-point', 'data_layer_collector',
        '--project', '${PROJECT_ID}',
        '--timeout', '540s',
        '--memory', '256MB',
        '--region', '${_REGION}',
        '--service-account', '${_SERVICE_ACCOUNT}'
    ]
timeout: 1200s
substitutions:
  _SERVICE_NAME: "datalayer-tests-push"

options:
  logging: 'CLOUD_LOGGING_ONLY'
